# AlertManager Configuration
# Routes alerts to appropriate channels

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree
route:
  receiver: 'default-receiver'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      group_wait: 5s
      repeat_interval: 5m

    # Warning alerts - batched notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 4h

    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 24h

# Receivers configuration
receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@sergas.com'
        from: 'alerts@sergas.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'alerts@sergas.com'
        auth_password: 'your-app-password'

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#sergas-critical-alerts'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    pagerduty_configs:
      - service_key: 'YOUR-PAGERDUTY-KEY'

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#sergas-warnings'
        title: 'Warning: {{ .GroupLabels.alertname }}'

  - name: 'info-alerts'
    email_configs:
      - to: 'team@sergas.com'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
